version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@localhost:5432/prediction_db?schema=public
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/usr/src/app
    command: >
      sh -c "npx prisma migrate deploy &&
             node src/app.js"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: prediction_db
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6

volumes:
  postgres-data:
